- name: Install Base System
  pacman: name={{item}} state=installed
  with_items:
    - git
    - openvpn
    - easy-rsa
    - vpnc
    - p7zip
    - unrar
    - aspell-es
    - hunspell-es
    - iotop
    - htop
    - scrot
    - tmux
    - screenfetch
    - keychain
    - vim
    - openssh
    - syncthing
    - zsh
    - rsync
    - net-tools
    - expect
    - sudo
    - gpm
    - bwm-ng
    - cowfortune
    - lolcat


- systemd: state=started enabled=yes name=gpm
