- name: Install Desktop Aplication
  pacman: name={{item}} state=installed
  with_items:
    - gdm
    - gnome
    - gnome-tweak-tool
    - ttf-liberation
    - ttf-anonymous-pro
    - ttf-droid
    - ttf-roboto
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
    - cantarell-fonts
    - gsfonts
    - amule
    - atom
    - audacity
    - calibre
    - evince
    - evolution
    - evolution-ews
    - gimp
    - gparted
    - libreoffice-fresh
    - openshot
#    - shutter
    - simplescreenrecorder
    - smplayer
    - terminator
    - texlive-most
    - texmaker
    - texstudio
    - transmission-gtk
    - networkmanager
    - networkmanager-openconnect
    - networkmanager-openvpn
    - networkmanager-vpnc
    - syncthing
    - syncthing-gtk
    - syncthing-inotify
    - usbutils
    - usb_modeswitch
    - modemmanager
    - mobile-broadband-provider-info
    - nm-connection-editor
    - modem-manager-gui
    - hexchat
    - remmina
    - freerdp


- systemd: state=started enabled=yes name=NetworkManager

- systemd: state=started enabled=yes name=ModemManager

- systemd: state=started enabled=yes name=gdm
