---
# tasks file for myArch
# Run the equivalent of "pacman -Syu" as a separate step
- pacman:
    name: archlinux-keyring
    state: latest
    update_cache: yes

- pacman:
    update_cache: yes
    upgrade: yes

- import_tasks: base.yml
- import_tasks: yaourt.yml
#- import_tasks: users.yml
- import_tasks: desktop.yml
- import_tasks: vm.yml
