- user:
    name: aldo
    comment: "Aldo Villagra"
    uid: 1100
    groups: wheel


- lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
